title: lotz's Haskell notebooks
description: IHaskellで書いたJupyter notebookを公開してます

github_username: lotz84
github_repo: "haskell-notebooks"

url: "https://lotz84.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/haskell-notebooks" # the subpath of your site, e.g. "/blog".

minima:
  social_links:
    twitter: lotz84_
    github: lotz84

use_math: true

show_description: true
show_image: true
show_tags: true

google_analytics: UA-38246049-20

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

include:
  - _pages

default_badges:
  github: true
  binder: false
  colab: false

# Everything below here should be left alone. Modifications may break fastpages
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate

# See https://jekyllrb.com/docs/pagination/
# For pagination to work, you cannot have index.md at the root of your repo, instead you must rename this file to index.html
paginate: 15
paginate_path: /page:num/

remote_theme: jekyll/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
