name:                haskell-notebooks
version:             0.1.0.0
github:              "githubuser/haskell-notebooks"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

  # extra-source-files:
  # - README.md

dependencies:
- ad
- base >= 4.7 && < 5
- cassava
- Chart
- extensible
- hmatrix
- microlens
- mwc-random
- numbers
- random-fu
- recursion-schemes
- semirings
- split
- unordered-containers

library:
  source-dirs: posts

